/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * API para o bootcamp de treinos
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from '../../fetch';
export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];


export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /**
     * @minimum 1
     * @maximum 9007199254740991
     */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay = typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];


export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /**
     * @minimum 1
     * @maximum 9007199254740991
     */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type ListWorkoutPlansParams = {
active?: string;
};

export type ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay[keyof typeof ListWorkoutPlans200ItemWorkoutDaysItemWeekDay];


export const ListWorkoutPlans200ItemWorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  sets: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  reps: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200ItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  weekDay: ListWorkoutPlans200ItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  exercises: ListWorkoutPlans200ItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200Item = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200ItemWorkoutDaysItem[];
};

export type ListWorkoutPlans400 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
};

export type StartWorkoutSession400 = {
  error: string;
  code: string;
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession403 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  completedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  startedAt: string;
};

export type UpdateWorkoutSession400 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession403 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItemWeekDay = typeof GetWorkoutPlan200WorkoutDaysItemWeekDay[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];


export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  estimatedDurationInSeconds: number;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan400 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan403 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  sets: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  reps: number;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  restTimeInSeconds: number;
};

export type GetWorkoutDay200WeekDay = typeof GetWorkoutDay200WeekDay[keyof typeof GetWorkoutDay200WeekDay];


export const GetWorkoutDay200WeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startedAt?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  completedAt?: string;
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  coverImageUrl?: string;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  estimatedDurationInSeconds: number;
  exercises: GetWorkoutDay200ExercisesItem[];
  weekDay: GetWorkoutDay200WeekDay;
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay400 = {
  error: string;
  code: string;
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay403 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type GetHomeData200TodayWorkoutDayWeekDay = typeof GetHomeData200TodayWorkoutDayWeekDay[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];


export const GetHomeData200TodayWorkoutDayWeekDay = {
  MONDAY: 'MONDAY',
  TUESDAY: 'TUESDAY',
  WEDNESDAY: 'WEDNESDAY',
  THURSDAY: 'THURSDAY',
  FRIDAY: 'FRIDAY',
  SATURDAY: 'SATURDAY',
  SUNDAY: 'SUNDAY',
} as const;

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
  estimatedDurationInSeconds: number;
  coverImageUrl?: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string;
  todayWorkoutDay: GetHomeData200TodayWorkoutDay;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData400 = {
  error: string;
  code: string;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  weightInGrams: number;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  heightInCentimeters: number;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  age: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData404 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /**
     * @maximum 9007199254740991
     * @exclusiveMinimum 0
     */
  weightInGrams: number;
  /**
     * @maximum 9007199254740991
     * @exclusiveMinimum 0
     */
  heightInCentimeters: number;
  /**
     * @maximum 9007199254740991
     * @exclusiveMinimum 0
     */
  age: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  userId: string;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  weightInGrams: number;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  heightInCentimeters: number;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  age: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData400 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData404 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
from: string;
/**
 * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
 */
to: string;
};

export type GetStats200ConsistencyByDay = {[key: string]: {
  workoutDayCompleted: boolean;
  workoutDayStarted: boolean;
}};

export type GetStats200 = {
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  completedWorkoutsCount: number;
  /**
     * @minimum 0
     * @maximum 1
     */
  conclusionRate: number;
  /**
     * @minimum 0
     * @maximum 9007199254740991
     */
  totalTimeInSeconds: number;
};

export type GetStats400 = {
  error: string;
  code: string;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

export type PostAiBodyMessagesItemRole = typeof PostAiBodyMessagesItemRole[keyof typeof PostAiBodyMessagesItemRole];


export const PostAiBodyMessagesItemRole = {
  system: 'system',
  user: 'user',
  assistant: 'assistant',
} as const;

export type PostAiBodyMessagesItemPartsItem = {
  type: string;
  [key: string]: unknown;
};

export type PostAiBodyMessagesItem = {
  id: string;
  role: PostAiBodyMessagesItemRole;
  parts: PostAiBodyMessagesItemPartsItem[];
  [key: string]: unknown;
};

export type PostAiBody = {
  /** @minItems 1 */
  messages: PostAiBodyMessagesItem[];
};

export type PostAi400 = {
  error: string;
  code: string;
};

export type PostAi401 = {
  error: string;
  code: string;
};

export type PostAi500 = {
  error: string;
  code: string;
};

export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201
  status: 201
}

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400
  status: 400
}

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401
  status: 401
}

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404
  status: 404
}

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500
  status: 500
}

export type createWorkoutPlanResponseSuccess = (createWorkoutPlanResponse201) & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (createWorkoutPlanResponse400 | createWorkoutPlanResponse401 | createWorkoutPlanResponse404 | createWorkoutPlanResponse500) & {
  headers: Headers;
};

export type createWorkoutPlanResponse = (createWorkoutPlanResponseSuccess | createWorkoutPlanResponseError)

export const getCreateWorkoutPlanUrl = () => {




  return `/workout-plans/`
}

/**
 * @summary Create a workout plan
 */
export const createWorkoutPlan = async (createWorkoutPlanBody: CreateWorkoutPlanBody, options?: Parameters<typeof customFetch>[1]): Promise<createWorkoutPlanResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createWorkoutPlanBody)
  }
);}



export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200Item[]
  status: 200
}

export type listWorkoutPlansResponse400 = {
  data: ListWorkoutPlans400
  status: 400
}

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401
  status: 401
}

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500
  status: 500
}

export type listWorkoutPlansResponseSuccess = (listWorkoutPlansResponse200) & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (listWorkoutPlansResponse400 | listWorkoutPlansResponse401 | listWorkoutPlansResponse500) & {
  headers: Headers;
};

export type listWorkoutPlansResponse = (listWorkoutPlansResponseSuccess | listWorkoutPlansResponseError)

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/workout-plans/?${stringifiedParams}` : `/workout-plans/`
}

/**
 * @summary List workout plans
 */
export const listWorkoutPlans = async (params?: ListWorkoutPlansParams, options?: Parameters<typeof customFetch>[1]): Promise<listWorkoutPlansResponse> => {

  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201
  status: 201
}

export type startWorkoutSessionResponse400 = {
  data: StartWorkoutSession400
  status: 400
}

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401
  status: 401
}

export type startWorkoutSessionResponse403 = {
  data: StartWorkoutSession403
  status: 403
}

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404
  status: 404
}

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409
  status: 409
}

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500
  status: 500
}

export type startWorkoutSessionResponseSuccess = (startWorkoutSessionResponse201) & {
  headers: Headers;
};
export type startWorkoutSessionResponseError = (startWorkoutSessionResponse400 | startWorkoutSessionResponse401 | startWorkoutSessionResponse403 | startWorkoutSessionResponse404 | startWorkoutSessionResponse409 | startWorkoutSessionResponse500) & {
  headers: Headers;
};

export type startWorkoutSessionResponse = (startWorkoutSessionResponseSuccess | startWorkoutSessionResponseError)

export const getStartWorkoutSessionUrl = (workoutPlanId: string,
    workoutDayId: string,) => {




  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`
}

/**
 * @summary Start a workout session
 */
export const startWorkoutSession = async (workoutPlanId: string,
    workoutDayId: string, options?: Parameters<typeof customFetch>[1]): Promise<startWorkoutSessionResponse> => {

  return customFetch<startWorkoutSessionResponse>(getStartWorkoutSessionUrl(workoutPlanId,workoutDayId),
  {
    ...options,
    method: 'POST'


  }
);}



export type updateWorkoutSessionResponse200 = {
  data: UpdateWorkoutSession200
  status: 200
}

export type updateWorkoutSessionResponse400 = {
  data: UpdateWorkoutSession400
  status: 400
}

export type updateWorkoutSessionResponse401 = {
  data: UpdateWorkoutSession401
  status: 401
}

export type updateWorkoutSessionResponse403 = {
  data: UpdateWorkoutSession403
  status: 403
}

export type updateWorkoutSessionResponse404 = {
  data: UpdateWorkoutSession404
  status: 404
}

export type updateWorkoutSessionResponse500 = {
  data: UpdateWorkoutSession500
  status: 500
}

export type updateWorkoutSessionResponseSuccess = (updateWorkoutSessionResponse200) & {
  headers: Headers;
};
export type updateWorkoutSessionResponseError = (updateWorkoutSessionResponse400 | updateWorkoutSessionResponse401 | updateWorkoutSessionResponse403 | updateWorkoutSessionResponse404 | updateWorkoutSessionResponse500) & {
  headers: Headers;
};

export type updateWorkoutSessionResponse = (updateWorkoutSessionResponseSuccess | updateWorkoutSessionResponseError)

export const getUpdateWorkoutSessionUrl = (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,) => {




  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`
}

/**
 * @summary Update a workout session
 */
export const updateWorkoutSession = async (workoutPlanId: string,
    workoutDayId: string,
    sessionId: string,
    updateWorkoutSessionBody: UpdateWorkoutSessionBody, options?: Parameters<typeof customFetch>[1]): Promise<updateWorkoutSessionResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<updateWorkoutSessionResponse>(getUpdateWorkoutSessionUrl(workoutPlanId,workoutDayId,sessionId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateWorkoutSessionBody)
  }
);}



export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200
  status: 200
}

export type getWorkoutPlanResponse400 = {
  data: GetWorkoutPlan400
  status: 400
}

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401
  status: 401
}

export type getWorkoutPlanResponse403 = {
  data: GetWorkoutPlan403
  status: 403
}

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404
  status: 404
}

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500
  status: 500
}

export type getWorkoutPlanResponseSuccess = (getWorkoutPlanResponse200) & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (getWorkoutPlanResponse400 | getWorkoutPlanResponse401 | getWorkoutPlanResponse403 | getWorkoutPlanResponse404 | getWorkoutPlanResponse500) & {
  headers: Headers;
};

export type getWorkoutPlanResponse = (getWorkoutPlanResponseSuccess | getWorkoutPlanResponseError)

export const getGetWorkoutPlanUrl = (workoutPlanId: string,) => {




  return `/workout-plans/${workoutPlanId}`
}

/**
 * @summary Get a workout plan
 */
export const getWorkoutPlan = async (workoutPlanId: string, options?: Parameters<typeof customFetch>[1]): Promise<getWorkoutPlanResponse> => {

  return customFetch<getWorkoutPlanResponse>(getGetWorkoutPlanUrl(workoutPlanId),
  {
    ...options,
    method: 'GET'


  }
);}



export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200
  status: 200
}

export type getWorkoutDayResponse400 = {
  data: GetWorkoutDay400
  status: 400
}

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401
  status: 401
}

export type getWorkoutDayResponse403 = {
  data: GetWorkoutDay403
  status: 403
}

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404
  status: 404
}

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500
  status: 500
}

export type getWorkoutDayResponseSuccess = (getWorkoutDayResponse200) & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (getWorkoutDayResponse400 | getWorkoutDayResponse401 | getWorkoutDayResponse403 | getWorkoutDayResponse404 | getWorkoutDayResponse500) & {
  headers: Headers;
};

export type getWorkoutDayResponse = (getWorkoutDayResponseSuccess | getWorkoutDayResponseError)

export const getGetWorkoutDayUrl = (workoutPlanId: string,
    workoutDayId: string,) => {




  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`
}

/**
 * @summary Get a workout day
 */
export const getWorkoutDay = async (workoutPlanId: string,
    workoutDayId: string, options?: Parameters<typeof customFetch>[1]): Promise<getWorkoutDayResponse> => {

  return customFetch<getWorkoutDayResponse>(getGetWorkoutDayUrl(workoutPlanId,workoutDayId),
  {
    ...options,
    method: 'GET'


  }
);}



export type getHomeDataResponse200 = {
  data: GetHomeData200
  status: 200
}

export type getHomeDataResponse400 = {
  data: GetHomeData400
  status: 400
}

export type getHomeDataResponse401 = {
  data: GetHomeData401
  status: 401
}

export type getHomeDataResponse404 = {
  data: GetHomeData404
  status: 404
}

export type getHomeDataResponse500 = {
  data: GetHomeData500
  status: 500
}

export type getHomeDataResponseSuccess = (getHomeDataResponse200) & {
  headers: Headers;
};
export type getHomeDataResponseError = (getHomeDataResponse400 | getHomeDataResponse401 | getHomeDataResponse404 | getHomeDataResponse500) & {
  headers: Headers;
};

export type getHomeDataResponse = (getHomeDataResponseSuccess | getHomeDataResponseError)

export const getGetHomeDataUrl = (date: string,) => {




  return `/home/${date}`
}

/**
 * @summary Get home page data
 */
export const getHomeData = async (date: string, options?: Parameters<typeof customFetch>[1]): Promise<getHomeDataResponse> => {

  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date),
  {
    ...options,
    method: 'GET'


  }
);}



export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200
  status: 200
}

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401
  status: 401
}

export type getUserTrainDataResponse404 = {
  data: GetUserTrainData404
  status: 404
}

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500
  status: 500
}

export type getUserTrainDataResponseSuccess = (getUserTrainDataResponse200) & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (getUserTrainDataResponse401 | getUserTrainDataResponse404 | getUserTrainDataResponse500) & {
  headers: Headers;
};

export type getUserTrainDataResponse = (getUserTrainDataResponseSuccess | getUserTrainDataResponseError)

export const getGetUserTrainDataUrl = () => {




  return `/me/`
}

/**
 * @summary Get user train data
 */
export const getUserTrainData = async ( options?: Parameters<typeof customFetch>[1]): Promise<getUserTrainDataResponse> => {

  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200
  status: 200
}

export type upsertUserTrainDataResponse400 = {
  data: UpsertUserTrainData400
  status: 400
}

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401
  status: 401
}

export type upsertUserTrainDataResponse404 = {
  data: UpsertUserTrainData404
  status: 404
}

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500
  status: 500
}

export type upsertUserTrainDataResponseSuccess = (upsertUserTrainDataResponse200) & {
  headers: Headers;
};
export type upsertUserTrainDataResponseError = (upsertUserTrainDataResponse400 | upsertUserTrainDataResponse401 | upsertUserTrainDataResponse404 | upsertUserTrainDataResponse500) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse = (upsertUserTrainDataResponseSuccess | upsertUserTrainDataResponseError)

export const getUpsertUserTrainDataUrl = () => {




  return `/me/`
}

/**
 * @summary Upsertuser train data
 */
export const upsertUserTrainData = async (upsertUserTrainDataBody: UpsertUserTrainDataBody, options?: Parameters<typeof customFetch>[1]): Promise<upsertUserTrainDataResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(upsertUserTrainDataBody)
  }
);}



export type getStatsResponse200 = {
  data: GetStats200
  status: 200
}

export type getStatsResponse400 = {
  data: GetStats400
  status: 400
}

export type getStatsResponse401 = {
  data: GetStats401
  status: 401
}

export type getStatsResponse500 = {
  data: GetStats500
  status: 500
}

export type getStatsResponseSuccess = (getStatsResponse200) & {
  headers: Headers;
};
export type getStatsResponseError = (getStatsResponse400 | getStatsResponse401 | getStatsResponse500) & {
  headers: Headers;
};

export type getStatsResponse = (getStatsResponseSuccess | getStatsResponseError)

export const getGetStatsUrl = (params: GetStatsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/stats/?${stringifiedParams}` : `/stats/`
}

/**
 * @summary Get user workout stats
 */
export const getStats = async (params: GetStatsParams, options?: Parameters<typeof customFetch>[1]): Promise<getStatsResponse> => {

  return customFetch<getStatsResponse>(getGetStatsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type postAiResponse200 = {
  data: unknown
  status: 200
}

export type postAiResponse400 = {
  data: PostAi400
  status: 400
}

export type postAiResponse401 = {
  data: PostAi401
  status: 401
}

export type postAiResponse500 = {
  data: PostAi500
  status: 500
}

export type postAiResponseSuccess = (postAiResponse200) & {
  headers: Headers;
};
export type postAiResponseError = (postAiResponse400 | postAiResponse401 | postAiResponse500) & {
  headers: Headers;
};

export type postAiResponse = (postAiResponseSuccess | postAiResponseError)

export const getPostAiUrl = () => {




  return `/ai/`
}

/**
 * @summary Chat with AI personal trainer
 */
export const postAi = async (postAiBody: PostAiBody, options?: Parameters<typeof customFetch>[1]): Promise<postAiResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<postAiResponse>(getPostAiUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postAiBody)
  }
);}
